[pre-commit]
parallel = true

[pre-commit.commands.check-js]
glob = "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc,yml,yaml}"
run = "pnpm biome check --no-errors-on-unmatched {staged_files}"

[pre-commit.commands.check-toml]
glob = "*.toml"
run = "test -z \"{staged_files}\" || (pnpm taplo format {staged_files} && git update-index --again)"

[commit-msg.scripts."commitlint.sh"]
runner = "bash"
